<?php

namespace Modules\LlmModule\Services\Adapters;

use App\Http\Services\Http\HttpClientService;

abstract class LLMBaseAdapter
{
    protected $apiKey;
    protected $baseUrl;
    protected $model;
    protected $httpClient;

    /**
     * @param string $apiKey
     * @param string $baseUrl
     * @param string $model
     * @param HttpClientService $httpClient
     */
    public function __construct($apiKey, $baseUrl, $model, HttpClientService $httpClient)
    {
        $this->apiKey = $apiKey;
        $this->baseUrl = rtrim($baseUrl, '/');
        $this->httpClient = $httpClient;
        $this->model = $model;
    }

    /**
     * Abstract method that each adapter must implement to make a call to the LLM.
     *
     * @param string $prompt
     * @param array  $options Additional options specific to each model (max_tokens, model, etc.)
     * @return string The response generated by the LLM
     */
    abstract public function call($prompt, array $options = []): string;


    /**
     * Abstract method that each adapter must implement to make a batch call to the LLM.
     * 
     * @param array $prompts
     * @param array $options
     * @return array The responses generated by the LLM
     */
    abstract public function batch(array $prompts, array $options = []): array;
}
